version: "3"

services:
  nodeos:
    image: eosio/eos-dev:v1.5.2
    restart: unless-stopped
    volumes:
      - ${PWD}/work:/work
      - ${PWD}/data:/mnt/dev/data
      - ${PWD}/config:/mnt/dev/config
    stop_signal: SIGINT
    stop_grace_period: 5m
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    command:
      - /opt/eosio/bin/nodeos
      - -e
      - -p
      - eosio
      - --filter-on=*
      - -d
      - /mnt/dev/data
      - --config-dir=/mnt/dev/config
      - --access-control-allow-origin=*
      - --contracts-console
      - --http-server-address=0.0.0.0:8888
      - --http-validate-host=false
      - --plugin=eosio::producer_plugin
      - --plugin=eosio::history_plugin
      - --plugin=eosio::chain_api_plugin
      - --plugin=eosio::history_api_plugin
      - --plugin=eosio::http_plugin
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
